import type { Metadata } from "next";
import "./globals.css";
import ConvexClietProvider from "@/providers/convex-client-provider";
import { Toaster } from "@/components/ui/toaster";
import { ModalProvider } from "@/providers/modal-provider";
import { ThemeProvider } from "@/providers/theme-provider";

export const metadata: Metadata = {
  title: "Realtime Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConvexClietProvider>
          <ThemeProvider>
            <Toaster richColors />
            <ModalProvider />
            {children}
          </ThemeProvider>
        </ConvexClietProvider>
      </body>
    </html>
  );
}
